
# Настройки  прототипа
stream:
# Входной RTSP-поток
  input_rtsp_url: "rtsp://127.0.0.1:8554/live"
# Выходной RTSP-поток
  output_rtsp_url: "rtsp://127.0.0.1:8554/preview"
# Включить выходную трансляцию
  enable_output_stream: true

camera:
# Использовать HW-ускорение для декодирования видео
  use_hwaccel: true

model_input:
# Ширина входного кадра
  width: 640
# Высота входного кадра
  height: 640

detector:
# Путь к модели YOLO
  model_path: models/yolov8s_japan_best.pt
# Порог уверенности для детекции
  confidence_threshold: 0.05
