# Конфигурация сервиса

# Конфигурация тестового входного RTSP потока
# Эти настройки используются скриптами публикации тестового видео
vlc:
  video: test_videos/video_1.mkv
  rtsp_port: 8554
  rtsp_path: live

# Настройки Python-сервиса обработки видео
stream:
  input_rtsp_url: "rtsp://127.0.0.1:8554/live"
  output_rtsp_url: "rtsp://127.0.0.1:8554/preview"
  enable_output_stream: true

camera:
  use_hwaccel: true

preview:
  width: 640
  height: 640
