# Конфиг для локального запуска симулятора RTSP и MVP

# Параметры HTTP/API управления MVP.
# Используется утилитой CLI.
mvp_control_ip: 127.0.0.1
mvp_control_port: 8081

# Путь к видеофайлу относительно корня проекта.
# Этот файл будет зацикленно публиковаться симулятором видеокамеры.
video: test_videos/check1.mkv

# Параметры выходного RTSP-потока, иммитатора видеокамеры.
# По этому адресу публикуется поток из видеофайла.
simulator_host: 127.0.0.1
simulator_port: 8554
simulator_path: live


# Параметры выходного RTSP-потока прототипа.
# Используется MP плеером для отображения видео
output_host: 127.0.0.1
output_port: 8554
output_path: preview

