# training/configs/train/args.yaml
# Конфиг обучения YOLO12n 

# Оптимизатор и LR
optimizer: auto      # в ноутбуке стоит optimizer=auto
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 5.0   # в базе 5, у коллеги было 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Веса лоссов
box: 7.5
cls: 0.5
dfl: 1.5
nbs: 64

# Аугментации
hsv_s: 0.7
hsv_v: 0.4
translate: 0.1
scale: 0.5
fliplr: 0.5
mosaic: 1.0          # в базе 0
mixup: 0.0
copy_paste: 0.0
erasing: 0.4

# Чекпоинты
save: true
save_period: 5
plots: true

# Общее число эпох
epochs: 100

# Останов если нет прогресса обучения
patience: 30 
